// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kweaver-ai/decision-agent/agent-factory/src/port/driven/ihttpaccess/iagentfactoryacc (interfaces: IAgentFactoryHttpAcc)
//
// Generated by this command:
//
//	mockgen -package agentfactorymock -destination ./agentfactorymock/agent_factory.go github.com/kweaver-ai/decision-agent/agent-factory/src/port/driven/ihttpaccess/iagentfactoryacc IAgentFactoryHttpAcc
//

// Package agentfactorymock is a generated GoMock package.
package agentfactorymock

import (
	context "context"
	reflect "reflect"

	afhttpdto "github.com/kweaver-ai/decision-agent/agent-factory/src/drivenadapter/httpaccess/agentfactoryhttp/afhttpdto"
	gomock "go.uber.org/mock/gomock"
)

// MockIAgentFactoryHttpAcc is a mock of IAgentFactoryHttpAcc interface.
type MockIAgentFactoryHttpAcc struct {
	ctrl     *gomock.Controller
	recorder *MockIAgentFactoryHttpAccMockRecorder
	isgomock struct{}
}

// MockIAgentFactoryHttpAccMockRecorder is the mock recorder for MockIAgentFactoryHttpAcc.
type MockIAgentFactoryHttpAccMockRecorder struct {
	mock *MockIAgentFactoryHttpAcc
}

// NewMockIAgentFactoryHttpAcc creates a new mock instance.
func NewMockIAgentFactoryHttpAcc(ctrl *gomock.Controller) *MockIAgentFactoryHttpAcc {
	mock := &MockIAgentFactoryHttpAcc{ctrl: ctrl}
	mock.recorder = &MockIAgentFactoryHttpAccMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAgentFactoryHttpAcc) EXPECT() *MockIAgentFactoryHttpAccMockRecorder {
	return m.recorder
}

// CheckAgentUsePermission mocks base method.
func (m *MockIAgentFactoryHttpAcc) CheckAgentUsePermission(ctx context.Context, req *afhttpdto.CheckPmsReq) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAgentUsePermission", ctx, req)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAgentUsePermission indicates an expected call of CheckAgentUsePermission.
func (mr *MockIAgentFactoryHttpAccMockRecorder) CheckAgentUsePermission(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAgentUsePermission", reflect.TypeOf((*MockIAgentFactoryHttpAcc)(nil).CheckAgentUsePermission), ctx, req)
}
