// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/app/:app_key/chat/completion": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "与 Agent 进行对话交互，支持流式响应",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "Agent 对话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "应用 Key",
                        "name": "app_key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "对话请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagger.ChatReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/swagger.ChatResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    }
                }
            }
        },
        "/v1/app/:app_key/chat/resume": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "恢复之前的对话会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "恢复对话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "应用 Key",
                        "name": "app_key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "恢复请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagger.ResumeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    }
                }
            }
        },
        "/v1/app/:app_key/conversation": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取指定应用的会话列表，支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Conversation"
                ],
                "summary": "获取会话列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "应用 Key",
                        "name": "app_key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量，默认10",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建一个新的会话会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Conversation"
                ],
                "summary": "初始化会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "应用 Key",
                        "name": "app_key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "初始化请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/conversationreq.InitReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    }
                }
            }
        },
        "/v1/app/:app_key/conversation/:id": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据会话 ID 获取会话详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Conversation"
                ],
                "summary": "获取会话详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "应用 Key",
                        "name": "app_key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    },
                    "404": {
                        "description": "会话不存在",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    }
                }
            }
        },
        "/v1/file/check": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "检查文件是否存在于知识库中",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "文件检查",
                "parameters": [
                    {
                        "description": "文件检查请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/agentreq.FileCheck"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    }
                }
            }
        },
        "/v3/product": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取产品列表，支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "获取产品列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量，默认10",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/productresp.ListRes"
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建一个新的产品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "创建产品",
                "parameters": [
                    {
                        "description": "产品信息",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/productreq.CreateReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/productresp.CreateRes"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    }
                }
            }
        },
        "/v3/product/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据产品 ID 获取产品详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "获取产品详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "产品 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/productresp.DetailRes"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    },
                    "404": {
                        "description": "产品不存在",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新产品信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "更新产品",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "产品 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "产品信息",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/productreq.UpdateReq"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    },
                    "404": {
                        "description": "产品不存在",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据产品 ID 删除产品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "删除产品",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "产品 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    },
                    "404": {
                        "description": "产品不存在",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "agentreq.FileCheck": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "agentreq.ModifiedArg": {
            "type": "object",
            "properties": {
                "key": {
                    "description": "参数名称",
                    "type": "string"
                },
                "value": {
                    "description": "参数值"
                }
            }
        },
        "agentreq.ResumeHandle": {
            "type": "object",
            "properties": {
                "current_block": {
                    "description": "当前代码块索引",
                    "type": "integer"
                },
                "frame_id": {
                    "description": "执行帧ID",
                    "type": "string"
                },
                "interrupt_type": {
                    "description": "中断类型",
                    "type": "string"
                },
                "restart_block": {
                    "description": "是否重启代码块",
                    "type": "boolean"
                },
                "resume_token": {
                    "description": "恢复令牌",
                    "type": "string"
                },
                "snapshot_id": {
                    "description": "快照ID",
                    "type": "string"
                }
            }
        },
        "agentreq.ResumeInterruptInfo": {
            "type": "object",
            "required": [
                "action",
                "resume_handle"
            ],
            "properties": {
                "action": {
                    "description": "操作类型: confirm | skip",
                    "type": "string"
                },
                "modified_args": {
                    "description": "修改后的参数",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/agentreq.ModifiedArg"
                    }
                },
                "resume_handle": {
                    "description": "恢复句柄",
                    "allOf": [
                        {
                            "$ref": "#/definitions/agentreq.ResumeHandle"
                        }
                    ]
                }
            }
        },
        "agentreq.SelectedFile": {
            "type": "object",
            "required": [
                "file_name"
            ],
            "properties": {
                "file_name": {
                    "description": "文件名",
                    "type": "string"
                }
            }
        },
        "agentreq.Tool": {
            "type": "object",
            "properties": {
                "session_id": {
                    "type": "string"
                },
                "tool_args": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/agentreq.ToolArg"
                    }
                },
                "tool_name": {
                    "type": "string"
                }
            }
        },
        "agentreq.ToolArg": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "type": {},
                "value": {
                    "description": "NOTE： 值类型不确定可能是string、array"
                }
            }
        },
        "cdaenum.ConversationMsgRole": {
            "type": "string",
            "enum": [
                "user",
                "assistant"
            ],
            "x-enum-varnames": [
                "MsgRoleUser",
                "MsgRoleAssistant"
            ]
        },
        "cdaenum.ConversationMsgStatus": {
            "type": "string",
            "enum": [
                "received",
                "processed",
                "processing",
                "succeded",
                "failed",
                "cancelled"
            ],
            "x-enum-varnames": [
                "MsgStatusReceived",
                "MsgStatusProcessed",
                "MsgStatusProcessing",
                "MsgStatusSucceded",
                "MsgStatusFailed",
                "MsgStatusCancelled"
            ]
        },
        "chatopt.ChatOption": {
            "type": "object",
            "properties": {
                "enable_dependency_cache": {
                    "description": "是否需要使用缓存",
                    "type": "boolean"
                },
                "is_need_doc_retrival_post_process": {
                    "description": "是否需要文档检索后处理",
                    "type": "boolean"
                },
                "is_need_history": {
                    "description": "是否需要历史上下文",
                    "type": "boolean"
                },
                "is_need_progress": {
                    "description": "是否需要progress",
                    "type": "boolean"
                }
            }
        },
        "chatresenum.AnswerType": {
            "type": "string",
            "enum": [
                "prompt",
                "explore",
                "other",
                "explore",
                "prompt",
                "other"
            ],
            "x-enum-comments": {
                "AnswerTypeExplore": "explore",
                "AnswerTypeOther": "other（除了 prompt 和 explore以外的）",
                "AnswerTypePrompt": "prompt，格式如：{\"answer\":\"xxx\",\"think\":\"xxx\"}"
            },
            "x-enum-varnames": [
                "AnswerTypeExplore",
                "AnswerTypePrompt",
                "AnswerTypeOther"
            ]
        },
        "comvalobj.LLMMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "conversationmsgvo.Message": {
            "type": "object",
            "properties": {
                "agent_info": {
                    "$ref": "#/definitions/valueobject.AgentInfo"
                },
                "content": {},
                "content_type": {
                    "$ref": "#/definitions/chatresenum.AnswerType"
                },
                "conversation_id": {
                    "type": "string"
                },
                "ext": {
                    "description": "扩展字段",
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "reply_id": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/cdaenum.ConversationMsgRole"
                },
                "status": {
                    "$ref": "#/definitions/cdaenum.ConversationMsgStatus"
                }
            }
        },
        "conversationreq.InitReq": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "description": "agent id",
                    "type": "string"
                },
                "agent_version": {
                    "description": "agent version",
                    "type": "string"
                },
                "executor_version": {
                    "description": "executor version v1 或 v2 默认v2",
                    "type": "string"
                },
                "temparea_id": {
                    "description": "临时区域ID",
                    "type": "string"
                },
                "title": {
                    "description": "conversation 标题",
                    "type": "string"
                },
                "visitor_type": {
                    "description": "访客类型  user / app",
                    "type": "string"
                }
            }
        },
        "productreq.CreateReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "key": {
                    "description": "产品标识，唯一",
                    "type": "string",
                    "maxLength": 50,
                    "example": "smart-customer-service"
                },
                "name": {
                    "description": "产品名称",
                    "type": "string",
                    "maxLength": 50,
                    "example": "智能客服"
                },
                "profile": {
                    "description": "产品简介",
                    "type": "string",
                    "maxLength": 100,
                    "example": "这是一个智能客服产品"
                }
            }
        },
        "productreq.UpdateReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "产品名称",
                    "type": "string",
                    "maxLength": 50,
                    "example": "智能客服"
                },
                "profile": {
                    "description": "产品简介",
                    "type": "string",
                    "maxLength": 100,
                    "example": "这是一个智能客服产品"
                }
            }
        },
        "productresp.CreateRes": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "产品ID",
                    "type": "integer",
                    "example": 12345
                },
                "key": {
                    "description": "产品Key",
                    "type": "string",
                    "example": "smart-customer-service"
                }
            }
        },
        "productresp.DetailRes": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间（时间戳，单位：ms）",
                    "type": "integer"
                },
                "id": {
                    "description": "产品ID",
                    "type": "integer"
                },
                "key": {
                    "description": "产品标识",
                    "type": "string"
                },
                "name": {
                    "description": "产品名称",
                    "type": "string"
                },
                "profile": {
                    "description": "产品简介",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间（时间戳，单位：ms）",
                    "type": "integer"
                }
            }
        },
        "productresp.ListItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间（时间戳，单位：ms）",
                    "type": "integer"
                },
                "id": {
                    "description": "产品ID",
                    "type": "integer"
                },
                "key": {
                    "description": "产品标识",
                    "type": "string"
                },
                "name": {
                    "description": "产品名称",
                    "type": "string"
                },
                "profile": {
                    "description": "产品简介",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间（时间戳，单位：ms）",
                    "type": "integer"
                }
            }
        },
        "productresp.ListRes": {
            "type": "object",
            "properties": {
                "entries": {
                    "description": "产品列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/productresp.ListItem"
                    }
                },
                "total": {
                    "description": "产品总数",
                    "type": "integer"
                }
            }
        },
        "rest.BaseError": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "错误描述",
                    "type": "string"
                },
                "error_code": {
                    "description": "错误码",
                    "type": "string"
                },
                "error_details": {
                    "description": "详细内容"
                },
                "error_link": {
                    "description": "错误链接",
                    "type": "string"
                },
                "solution": {
                    "description": "解决方法",
                    "type": "string"
                }
            }
        },
        "rest.HTTPError": {
            "type": "object",
            "properties": {
                "baseError": {
                    "$ref": "#/definitions/rest.BaseError"
                },
                "httpcode": {
                    "type": "integer"
                },
                "language": {
                    "type": "string"
                }
            }
        },
        "swagger.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "details": {
                    "type": "string",
                    "example": "详细错误信息"
                },
                "message": {
                    "type": "string",
                    "example": "请求参数错误"
                }
            }
        },
        "swagger.ChatReq": {
            "type": "object",
            "properties": {
                "agent_app_key": {
                    "description": "agent app key",
                    "type": "string"
                },
                "agent_id": {
                    "description": "agentID",
                    "type": "string"
                },
                "agent_key": {
                    "description": "agentKey",
                    "type": "string"
                },
                "agent_version": {
                    "description": "agent版本",
                    "type": "string"
                },
                "chat_mode": {
                    "description": "聊天模式",
                    "type": "string"
                },
                "chat_option": {
                    "$ref": "#/definitions/chatopt.ChatOption"
                },
                "confirm_plan": {
                    "description": "是否确认计划",
                    "type": "boolean"
                },
                "conversation_id": {
                    "description": "会话ID",
                    "type": "string"
                },
                "custom_querys": {
                    "description": "自定义查询",
                    "type": "object",
                    "additionalProperties": true
                },
                "executor_version": {
                    "description": "executor version v1 或 v2 默认v2",
                    "type": "string"
                },
                "history": {
                    "description": "历史上下文",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/comvalobj.LLMMessage"
                    }
                },
                "history_limit": {
                    "description": "历史上下文限制,默认10轮",
                    "type": "integer"
                },
                "inc_stream": {
                    "description": "是否增量返回",
                    "type": "boolean"
                },
                "interrupted_assistant_message_id": {
                    "description": "中断的助手消息ID",
                    "type": "string"
                },
                "model_name": {
                    "description": "指定使用的大模型名称",
                    "type": "string"
                },
                "query": {
                    "description": "查询内容",
                    "type": "string"
                },
                "regenerate_assistant_message_id": {
                    "description": "重新生成的助手消息ID",
                    "type": "string"
                },
                "regenerate_user_message_id": {
                    "description": "重新生成的用户消息ID",
                    "type": "string"
                },
                "selected_files": {
                    "description": "用户选择的临时区文件",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/agentreq.SelectedFile"
                    }
                },
                "stream": {
                    "description": "NOTE: 新增stream参数，控制流式返回",
                    "type": "boolean"
                },
                "tool": {
                    "description": "工具",
                    "allOf": [
                        {
                            "$ref": "#/definitions/agentreq.Tool"
                        }
                    ]
                }
            }
        },
        "swagger.ChatResp": {
            "type": "object",
            "properties": {
                "agent_run_id": {
                    "description": "Agent运行ID（从Executor返回）",
                    "type": "string"
                },
                "assistant_message_id": {
                    "description": "助手消息ID",
                    "type": "string"
                },
                "conversation_id": {
                    "description": "会话ID",
                    "type": "string"
                },
                "error": {
                    "description": "Status  string                    ` + "`" + `json:\"status\"` + "`" + `  // 状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.HTTPError"
                        }
                    ]
                },
                "message": {
                    "description": "消息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/conversationmsgvo.Message"
                        }
                    ]
                },
                "user_message_id": {
                    "description": "用户消息ID",
                    "type": "string"
                }
            }
        },
        "swagger.ResumeReq": {
            "type": "object",
            "required": [
                "conversation_id"
            ],
            "properties": {
                "agent_run_id": {
                    "description": "Agent运行ID（中断恢复时必填）",
                    "type": "string"
                },
                "conversation_id": {
                    "description": "会话ID",
                    "type": "string"
                },
                "resume_interrupt_info": {
                    "description": "中断恢复信息（为nil时走原逻辑）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/agentreq.ResumeInterruptInfo"
                        }
                    ]
                }
            }
        },
        "valueobject.AgentInfo": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "agent_name": {
                    "type": "string"
                },
                "agent_status": {
                    "type": "string"
                },
                "agent_version": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer {token} - 需要有效的 OAuth 访问令牌",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:30777",
	BasePath:         "/api/agent-factory",
	Schemes:          []string{},
	Title:            "Agent Factory API",
	Description:      "Agent Factory 智能体工厂 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
